candidature:
    path:     /
    defaults: { _controller: "BseCandidatureBundle:Candidature:index" }

#candidature_s:
#    path:     /{id}/s_s987321e
#    defaults: { _controller: "BseCandidatureBundle:Candidature:show" }

candidature_new:
    path:     /new/{first}
    defaults: { _controller: "BseCandidatureBundle:Candidature:new", first:'null' }

candidature_create:
    path:     /create
    defaults: { _controller: "BseCandidatureBundle:Candidature:create" }
    requirements: { _method: post }

candidature_edit:
    path:     /{id}/edit
    defaults: { _controller: "BseCandidatureBundle:Candidature:edit" }

candidature_update:
    path:     /{id}/update
    defaults: { _controller: "BseCandidatureBundle:Candidature:update" }
    requirements: { _method: post|put }

#candidature_d:
#    path:     /{id}/d_s987321e
#    defaults: { _controller: "BseCandidatureBundle:Candidature:delete" }
#    requirements: { _method: post|delete }

candidature_procedure:
    path:     /procedure
    defaults: { _controller: "BseCandidatureBundle:Candidature:procedure" }