bse_selection_welcome:
    path:     /
    defaults: { _controller: BseSelectionBundle:Default:index }

bse_selection_execute:
    path:     /execute
    defaults: { _controller: BseSelectionBundle:Default:execute }
    requirements: { _method: post }
