bse_selection_welcome:
    path:     /
    defaults: { _controller: BseSelectionBundle:Default:index }

bse_selection_execute:
    path:     /execute
    defaults: { _controller: BseSelectionBundle:Default:execute }
    requirements: { _method: post }


bse_selection_export:
    path:     /export
    defaults: { _controller: BseSelectionBundle:Default:export }


#bse_export_csvFiles:
#    path:     /hidden/abcd9876yll/exportcsvfiles
#    defaults: { _controller: BseSelectionBundle:Default:exportCsvFiles }
